### ISSUE TITLE
github.com/imroc/req/v3/internal/http3 trouble

### ISSUE THREAD

**Issue by qiuyejianweinuan** [nekomeowww/go-pinecone#1]
```
# github.com/imroc/req/v3/internal/http3
../../pkg/mod/github.com/imroc/req/v3@v3.33.2/internal/http3/client.go:269:37: c.conn.HandshakeComplete().Done undefined (type <-chan struct{} has no field or method Done)

```

When I use this to operate a pinecone, this error will be reported. When I check the issue of IMROC, people are also discussing this error. So, how can I use your project normally

**Comment by nekomeowww** [comment]
> ```
> # github.com/imroc/req/v3/internal/http3
> ../../pkg/mod/github.com/imroc/req/v3@v3.33.2/internal/http3/client.go:269:37: c.conn.HandshakeComplete().Done undefined (type <-chan struct{} has no field or method Done)
> ```
> 
> When I use this to operate a pinecone, this error will be reported. When I check the issue of IMROC, people are also discussing this error. So, how can I use your project normally

Let me check it very quickly.

**Comment by nekomeowww** [comment]
> ```
> # github.com/imroc/req/v3/internal/http3
> ../../pkg/mod/github.com/imroc/req/v3@v3.33.2/internal/http3/client.go:269:37: c.conn.HandshakeComplete().Done undefined (type <-chan struct{} has no field or method Done)
> ```
> 
> When I use this to operate a pinecone, this error will be reported. When I check the issue of IMROC, people are also discussing this error. So, how can I use your project normally

It works really well on my side. I ran the tests, wrote a quick example, checked the application I used this library, there are no errors and building issues output.

So I bet your `github.com/imroc/req/v3` version is higher than `v0.33.0`? What was it?  And could you please downgrade your `github.com/imroc/req/v3` dependency?

I checked the issue you mentioned above: https://github.com/imroc/req/issues/232
And the author seems have conclude an resolution to this issue: https://github.com/imroc/req/issues/232#issuecomment-1519754898

**Comment by nekomeowww** [comment]
Closed due to in-activity
