### ISSUE TITLE
bug: malformed header: missing HTTP content-type

### ISSUE THREAD

**Issue by aldarisbm** [nekomeowww/go-pinecone#2]
` rpc error: code = Unknown desc = malformed header: missing HTTP content-type`

When trying to upsert, the `ListIndexes` function does work, but nothing on the grpc side

**Comment by aldarisbm** [comment]
this seems to be an error with the grpc package from pinecone

**Comment by nekomeowww** [comment]
Let me investigate.

**Comment by nekomeowww** [comment]
It turns out that Pinecone seems turned their gRPC services off therefore the official gRPC service client no longer works. I am working hard to wrap the REST API to replace the originals. Stay tuned.

**Comment by aldarisbm** [comment]
@nekomeowww  I have done a lot of the work here:

https://github.com/aldarisbm/go-pinecone/blob/main/vectors.go 

if you want to take some of this! most of them other than `DescribeIndexStats` is done, needs further testing, but preliminary testing works

**Comment by nekomeowww** [comment]
> @nekomeowww I have done a lot of the work here:
> 
> https://github.com/aldarisbm/go-pinecone/blob/main/vectors.go
> 
> if you want to take some of this! most of them other than `DescribeIndexStats` is done, needs further testing, but preliminary testing works

Wow! Amazing! Is that possible to create a Pull Request and move the existing implementations into `nekomeowww/go-pinecone`? If so, it is welcomed for you to contribute them.

**Comment by aldarisbm** [comment]
I can probably get out a  PR out sometime today!

**Comment by nekomeowww** [comment]
> I can probably get out a PR out sometime today!

Thank you very much!

**Comment by aldarisbm** [comment]
almost done with the PR, need to add unit tests

https://github.com/aldarisbm/go-pinecone/tree/adding-client

**Comment by nekomeowww** [comment]
Close due to implemented
